### PR TITLE
Make octoffers a Directly Executable CLI

### PR DESCRIPTION
**Pull request by ghost**
Fixes issue #14

### CODE REVIEW

**Comment by webgtx** [comment]
@oebelus thank you for the PR.

But issue isn't quite solved.

Try to run `octoffers help` after you install package. And you'll see this
```
(.venv) alex:octoffers/ (oebelus/devel✗) $ octoffers help                                                                                                                            [0:00:45]
Traceback (most recent call last):
  File "/home/alex/Desktop/work/side/octoffers/.venv/bin/octoffers", line 5, in <module>
    from octoffers import main
  File "/home/alex/Desktop/work/side/octoffers/octoffers/__init__.py", line 1, in <module>
    from octoffers.__main__ import main
  File "/home/alex/Desktop/work/side/octoffers/octoffers/__main__.py", line 2, in <module>
    from octoffers.platforms.djinni import Djinni
  File "/home/alex/Desktop/work/side/octoffers/octoffers/platforms/djinni.py", line 10, in <module>
    from platforms.driver import Driver
ModuleNotFoundError: No module named 'platforms'
```

2. We don't use poetry at this moment. Please remove `poetry.lock`.

**Comment by webgtx** [comment]
> @oebelus thank you for the PR.
> 
> But issue isn't quite solved.
> 
> Try to run `octoffers help` after you install package. And you'll see this
> 
> ```
> (.venv) alex:octoffers/ (oebelus/devel✗) $ octoffers help                                                                                                                            [0:00:45]
> Traceback (most recent call last):
>   File "/home/alex/Desktop/work/side/octoffers/.venv/bin/octoffers", line 5, in <module>
>     from octoffers import main
>   File "/home/alex/Desktop/work/side/octoffers/octoffers/__init__.py", line 1, in <module>
>     from octoffers.__main__ import main
>   File "/home/alex/Desktop/work/side/octoffers/octoffers/__main__.py", line 2, in <module>
>     from octoffers.platforms.djinni import Djinni
>   File "/home/alex/Desktop/work/side/octoffers/octoffers/platforms/djinni.py", line 10, in <module>
>     from platforms.driver import Driver
> ModuleNotFoundError: No module named 'platforms'
> ```
> 
> 2. We don't use poetry at this moment. Please remove `poetry.lock`.

I guess you can simply solve this by adding `octoffers.*` for each internal import

**Comment by ghost** [comment]
I have fixed the internal imports

**Comment by webgtx** [comment]
@oebelus do you even test it?
```
(.venv) alex:octoffers/ (oebelus/devel) $ octoffers help                             [2:28:26]
Traceback (most recent call last):
  File "/home/alex/Desktop/work/side/octoffers/.venv/bin/octoffers", line 5, in <module>
    from octoffers import main
  File "/home/alex/Desktop/work/side/octoffers/octoffers/__init__.py", line 1, in <module>
    from octoffers.__main__ import main
  File "/home/alex/Desktop/work/side/octoffers/octoffers/__main__.py", line 2, in <module>
    from octoffers.platforms.djinni import Djinni
  File "/home/alex/Desktop/work/side/octoffers/octoffers/platforms/djinni.py", line 12, in <module>
    from intergrations.chat_gpt import get_cover_letter_from_openai
ModuleNotFoundError: No module named 'intergrations'
```

**Comment by ghost** [comment]
I encountered an error because the `*.db` file was in `.gitignore`. So, I created a mock database, fixed the `integrations` and other imports. Now, I'm unable to resolve further errors as the Indeed module is located in `octoffers.platforms.private`, and it's not being imported correctly.
Error: 
```
File "C:\Users\imane\Downloads\Code\octoffers\octoffers\__main__.py", line 10, in __init__
    from octoffers.platforms.private import Indeed
ImportError: cannot import name 'Indeed' from 'octoffers.platforms.private' (unknown location)
```

**Comment by webgtx** [comment]
> I encountered an error because the `*.db` file was in `.gitignore`. So, I created a mock database, fixed the `integrations` and other imports. Now, I'm unable to resolve further errors as the Indeed module is located in `octoffers.platforms.private`, and it's not being imported correctly. Error:
> 
> ```
> File "C:\Users\imane\Downloads\Code\octoffers\octoffers\__main__.py", line 10, in __init__
>     from octoffers.platforms.private import Indeed
> ImportError: cannot import name 'Indeed' from 'octoffers.platforms.private' (unknown location)
> ```

Indeed is an optional driver

```python
        try:
            from octoffers.platforms.private import Indeed
            self.indeed = Indeed(profile=profile)

        except ModuleNotFoundError:
            print("Private drivers weren't found")
```

**Comment by webgtx** [comment]
@oebelus It works on my side now, what python version you running?

**Comment by ghost** [comment]
Python 3.12.7

**Comment by ghost** [comment]
I commented out the `try except` block and now it's working: 
```
>> octoffers djinni     

NAME
    octoffers djinni

SYNOPSIS
    octoffers djinni GROUP | COMMAND | VALUE

GROUPS
    GROUP is one of the following:

     chrome_args

     session_cookies

COMMANDS
    COMMAND is one of the following:

--(44%)--
```

**Comment by webgtx** [comment]
Alright, that issue with private driver is out of the scope. So I'll deal with it later.
You did your part, **thank you**.

**Pull request merged**
